name: TDD-Exercise
run-name: Testing Github Actions for Python script

on: [push]

jobs:
  trail-python-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'   

      - name: Run python script
        run: |
          python -m unittest
